inventory = {
    'all': {
        'children': {
            'web1': {
                'hosts': {}
            },
            'web2': {
                'hosts': {}
            }
        }
    }
}
